version: 2
jobs:
  required-1:
    docker:
      - image: circleci/node
    steps:
      - run:
          name: succeed
          command: exit 0
          no_output_timeout: 10s
  required-2:
    docker:
      - image: circleci/node
    steps:
      - run:
          name: succeed
          command: exit 0
          no_output_timeout: 10s
  optional-1:
    docker:
      - image: circleci/node
    steps:
      - run:
          name: fail
          command: exit 1
          no_output_timeout: 10s
  fan_in:
    docker:
      - image: circleci/node
    steps:
      - run:
          name: succeed
          command: exit 0
          no_output_timeout: 10s
workflows:
  version: 2
  optional_test:
    jobs:
      - required-1
      - required-2
      - optional-1
      - fan_in:
          requires:
            - required-1
            - required-2
            - optional-1
