version: 2
jobs:
  required-1:
    steps:
      - run:
        name: succeed
        command: return 0
        no_output_timeout: 10s
  required-2:
    steps:
      - run:
        name: succeed
        command: return 0
        no_output_timeout: 10s
  optional-1:
    steps:
      - run:
        name: fail
        command: return 1
        no_output_timeout: 10s
  fan_in:
    steps:
      - run:
        name: succeed
        command: return 0
        no_output_timeout: 10s
workflows:
  version: 2
  optional_test:
    jobs:
      - required-1
      - required-2
      - optional-1
      - fan_in:
        requires:
          - required-1
          - required-2
